# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84011f7ec5e00c2635ae101f5751459062b6829fa767fd62e518a2ac428c555822f5a22b595dd103bbcfd8b24608cfeea1a8ccea5a541892fc16cc4ad3292830

test:
  secret_key_base: 9c615036ab67818d56adc4b4fc4e9fe0139c81995b96a14f9cec3da0f02427860970377cc2e2e73b53344d6a4af43ffd0541b649b861fd2b81db7f534cd1df52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
